### ISSUE TITLE
recent Actions

### ISSUE THREAD

**Issue by OmarTahoun** [UIACC/codeforces-cli#8]
I will take on this one

**Comment by OmarTahoun** [comment]
@Sohieeb For recent actions is it optional or required for the user to enter the count.
or should there be a default count if the user didn't specify

**Comment by moadmmh** [comment]
same goes for coming contests

**Comment by Sohieb** [comment]
For now, the parser will only call the function if the user input the specified parameters and in the same order otherwise it will not work.
We will update it to handle options better later. But for now just implement the (recent actions) using the parameter passed to the function, and later when we update the parser we will assign a default value for the parameter so your function will not need to be modified.

**Comment by Sohieb** [comment]
The command returns the same blog multiple times. I tested it with -c 10, and it actually returned only 2 unique blogs, one of them 9 times and the other once.

Please test it again and modify the code to only return each unique blog post once.

**Comment by omar-abdulaziz** [comment]
On it
